//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComprasORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lente
    {
        public int IdLente { get; set; }
        public string Marca { get; set; }
        public float Precio { get; set; }
        public string Material { get; set; }
        public string TipoLente { get; set; }
    }
}
